username: somedefaultadminaccount

domains:
  mydomain.com:
    hosts:
      - server1201
      - server1202
      - server1299
      - switch01
      - switch02
      

    subdomains:
      dev:
        username: devadminusername
        hosts:
          - dev108
          - dev121

      lab:
        hosts:
          - minion1
          - minion2
          - minion3
          - minion4
